/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCheckbox: typeof import('./../components/AppCheckbox/index.vue')['default']
    AppFooter: typeof import('./../components/AppFooter/index.vue')['default']
    AppHeader: typeof import('./../components/AppHeader/index.vue')['default']
    Checkbox: typeof import('./../components/Checkbox/index.vue')['default']
    Marquee: typeof import('./../components/Marquee/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
